# Generated by Django 3.2 on 2024-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
